dist: xenial
sudo: required
language: node_js
node_js:
  - "node"
addons:
  apt:
    packages:
      - libmpv-dev
before_install:
  - |
    cd ~
    wget https://github.com/Kagami/nacl_sdk/archive/master.zip && unzip master.zip
    nacl_sdk-master/naclsdk update
    export NACL_SDK_ROOT=$HOME/nacl_sdk-master/pepper_49
    cd -
  # Force compilation of addon.
  - sed -i '/"_from":/d' package.json
notifications:
  email:
    on_success: never
